#!/usr/bin/env python3



import rospy

from geometry_msgs.msg import Twist

import sys, select, termios, tty

msg = """
Control Turtlebot2   Control Turtlebot3
-------------------------------------------
Moving around:
   u    i    o          q    w    e
   j    k    l          a    s    d
   m    ,    .          z    x    c

t/b : increase/decrease only linear speed by 10%
f/h : increase/decrease only angular speed by 10%

anything else : stop smoothly

CTRL-C to quit
"""

tb2moveBindings = {
        'i':(1,0),
        'o':(1,-1),
        'j':(0,1),
        'l':(0,-1),
        'u':(1,1),
        ',':(-1,0),
        '.':(-1,1),
        'm':(-1,-1),
	'k':(0,0),
           }
tb3moveBindings = {
        'w':(1,0),
        'e':(1,-1),
        'a':(0,1),
        'd':(0,-1),
        'q':(1,1),
        'x':(-1,0),
        'c':(-1,1),
        'z':(-1,-1),
	's':(0,0),
           }

speedBindings={
        't':(1.1,1),
        'b':(0.9,1),
        'f':(1,1.1),
        'h':(1,0.9),
          }

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

speed = .2
turn = 1

def vels(speed,turn):
    return "currently:\tspeed %s\tturn %s " % (speed,turn)

if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin)
    
    rospy.init_node('tb2_tb3_teleop')
    tb2pub = rospy.Publisher('/tb2/cmd_vel_mux/input/teleop', Twist, queue_size=5)
    tb3pub = rospy.Publisher('/tb3/cmd_vel', Twist, queue_size=5)

    x = 0
    th = 0
    status = 0
    count = 0
    acc = 0.1
    target_speed = 0
    target_turn = 0
    control_speed = 0
    control_turn = 0
    try:
        print(msg)
        print(vels(speed,turn))
        while(1):
            key = getKey()
            if key in tb2moveBindings.keys():
                x = tb2moveBindings[key][0]
                th = tb2moveBindings[key][1]
                count = 0

            elif key in tb3moveBindings.keys():
                x = tb3moveBindings[key][0]
                th = tb3moveBindings[key][1]
                count = 0
            elif key in speedBindings.keys():
                speed = speed * speedBindings[key][0]
                turn = turn * speedBindings[key][1]
                count = 0

                if (status == 14):
                    print(msg)
                status = (status + 1) % 15
                print(vels(speed,turn))
            else:
                count = count + 1
                if count > 4:
                    x = 0
                    th = 0
                if (key == '\x03'):
                    break

            target_speed = speed * x
            target_turn = turn * th

            if target_speed > control_speed:
                control_speed = min( target_speed, control_speed + 0.02 )
            elif target_speed < control_speed:
                control_speed = max( target_speed, control_speed - 0.02 )
            else:
                control_speed = target_speed

            if target_turn > control_turn:
                control_turn = min( target_turn, control_turn + 0.1 )
            elif target_turn < control_turn:
                control_turn = max( target_turn, control_turn - 0.1 )
            else:
                control_turn = target_turn

            twist = Twist()
            twist.linear.x = control_speed; twist.linear.y = 0; twist.linear.z = 0
            twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = control_turn
            if key in tb2moveBindings.keys():
                tb2pub.publish(twist)
                if (status == 14):
                    print(msg)
                status = (status + 1) % 15
                print('linear',twist.linear.x,'angular',twist.angular.z)
            elif key in tb3moveBindings.keys():
                tb3pub.publish(twist)
                if (status == 14):
                    print(msg)
                status = (status + 1) % 15
                print('linear',twist.linear.x,'angular',twist.angular.z)
            else:
                twist.linear.x = 0
                twist.angular.z = 0
                tb2pub.publish(twist)
                tb3pub.publish(twist)


            #print("loop: {0}".format(count))
            #print("target: vx: {0}, wz: {1}".format(target_speed, target_turn))
            #print("publihsed: vx: {0}, wz: {1}".format(twist.linear.x, twist.angular.z))

    except Exception as e:
        print(e)

    finally:
        twist = Twist()
        twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        tb2pub.publish(twist)
        tb3pub.publish(twist)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)

